# Generated by Django 5.1.1 on 2024-11-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_alter_proveedor_email_comprasenc_comprasdet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
